### ISSUE TITLE
Android N CTS RenderScript Failure on SKL

### ISSUE THREAD

**Issue by txu4** [android-ia/manifest#1]
There are 444 failures in CtsRenderscriptTestCases, which is due to process crash

Module  Passed  Failed  Total Tests
CtsRenderscriptTestCases    289 444 733
1.  Reproduce the issue 
   adb shell am instrument -w -r -e class android.renderscript.cts.refocus.RefocusTest android.renderscript.cts/android.support.test.runner.AndroidJUnitRunner
2.  Crash log, the librs.layered_filter_fast_d1new.so was dynamic generated in run-time.
   10-26 02:43:25.209  3780  3780 F DEBUG   : **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
   10-26 02:43:25.209  3780  3780 F DEBUG   : Build fingerprint: 'OAndroid/oandroid_64/oandroid_64:7.0/NRD90M/randy10091629:eng/test-keys'
   10-26 02:43:25.209  3780  3780 F DEBUG   : Revision: '0'
   10-26 02:43:25.209  3780  3780 F DEBUG   : ABI: 'x86_64'
   10-26 02:43:25.209  3780  3780 F DEBUG   : pid: 3749, tid: 3767, name: roidJUnitRunner  >>> android.renderscript.cts <<<
   10-26 02:43:25.209  3780  3780 F DEBUG   : signal 4 (SIGILL), code 2 (ILL_ILLOPN), fault addr 0x71888921c4c4
   10-26 02:43:25.209  3780  3780 F DEBUG   :     rax 0000000000000169  rbx 0000718886b62f00  rcx 000000000000011c  rdx 0000000000000039
   10-26 02:43:25.209  3780  3780 F DEBUG   :     rsi 000000000000002d  rdi 0000718886b62f00
   10-26 02:43:25.209  3780  3780 F DEBUG   :     r8  0000000000000000  r9  0000718883fc1400  r10 000071888ed1a208  r11 0000000000000206
   10-26 02:43:25.209  3780  3780 F DEBUG   :     r12 0000000000000004  r13 0000000000000000  r14 0000000000000014  r15 0000718886a56380
   10-26 02:43:25.209  3780  3780 F DEBUG   :     cs  0000000000000033  ss  000000000000002b
   10-26 02:43:25.209  3780  3780 F DEBUG   :     rip 000071888921c4c4  rbp 0000718886b62f00  rsp 000071888935e9a0  eflags 0000000000010206
   10-26 02:43:25.210  3780  3780 F DEBUG   :
   10-26 02:43:25.210  3780  3780 F DEBUG   : backtrace:
   10-26 02:43:25.210  3780  3780 F DEBUG   :     #00 pc 00000000000014c4  /data/user_de/0/android.renderscript.cts/code_cache/com.android.renderscript.cache/librs.layered_filter_fast_d1new.so
   10-26 02:43:25.508  1772  1790 I BootReceiver: Copying /data/tombstones/tombstone_03 to DropBox (SYSTEM_TOMBSTONE)
   10-26 02:43:25.515  1472  1472 W         : debuggerd: resuming target 3749
   10-26 02:43:25.516  1498  1498 I Zygote  : Process 3749 exited due to signal (4)
   10-26 02:43:25.520  1772  1784 I ActivityManager: Process android.renderscript.cts (pid 3749) has died
3.  Objdump the so and check the crash address.
   objdump -D librs.layered_filter_fast_d1new.so > librs.dump
   14c4:       62 f1 7d 08 6f 05 82    vmovdqa32 0x3e82(%rip),%xmm0        # 5350 <__bss_start>

The "vmovdqa32" is AVX-512 instruction, not supported by SKL i7-6770HQ , http://ark.intel.com/products/93341/Intel-Core-i7-6770HQ-Processor-6M-Cache-up-to-3_50-GHz. Need to investigate why the RS dynamic generated the machine code has AVX-512 instruction, like VMOVDQAxxx (which causes the process crash) and how to turn it off.

**Comment by qiming-shi** [comment]
The issue is caused by LLVM compiler. LLVM recognizes CPU by its model and name and sustains a .td file which describes all its features. Unfortunately LLVM only has one skylake model which supports AVX512. We need to ask LLVM experts to add another skylake mode for this i7-6770HQ.

**Comment by kalyankondapally** [comment]
@qiming-shi Any update ?

**Comment by qiming-shi** [comment]
We have raised the issue to LLVM team, but got slow response from them. We'll continue to push them.

Thanks

**Comment by txu4** [comment]
Qiming finds a patch in libbcc master, not in N dessert yet, can solve the issue.
Verified, all cases can pass now on SKL

`commit 0dde4d9533a2ad21c83cdba584198586bb590a41
Author: Yang Ni <yangni@google.com>
Date:   Mon Jun 13 11:18:40 2016 -0700

    Disable AVX support in bcc
    
    Bug: 28879581
    
    LLVM generates AVX code for long3 load/store, which treats a long3 value
    as 256 bits, while the RS runtime only allocates 192 bits for a long3
    element in an allocation.
    
    This CL disables AVX codegen to avoid this issue.
    
    Change-Id: Ia656a36c35a4cfbe620a555abb8b28c808843459

diff --git a/lib/Support/CompilerConfig.cpp b/lib/Support/CompilerConfig.cpp
index b2b3a55..87fcdad 100644
--- a/lib/Support/CompilerConfig.cpp
+++ b/lib/Support/CompilerConfig.cpp
@@ -238,6 +238,11 @@ bool CompilerConfig::initializeArch() {
     attributes.push_back("+sse4.2");
 #endif
 #endif // __HOST__
+
+    // LLVM generates AVX code that treats a long3 as 256 bits, while
+    // RenderScript considers a long3 192 bits (http://b/28879581)
+    attributes.push_back("-avx");
+
     break;
 #endif  // PROVIDE_X86_CODEGEN
 
@@ -265,6 +270,10 @@ bool CompilerConfig::initializeArch() {
       attributes.push_back("+f16c");
 #endif // __HOST__
 
+    // LLVM generates AVX code that treats a long3 as 256 bits, while
+    // RenderScript considers a long3 192 bits (http://b/28879581)
+    attributes.push_back("-avx");
+
     break;
 #endif  // PROVIDE_X86_CODEGEN
`

**Comment by txu4** [comment]
@kalyankondapally can you cherrypick this AOSP patch from Google master to android-ia?
It's in frameworks/compile/libbcc directory.

**Comment by kalyankondapally** [comment]
@txu4  Should be possible, can you give me direct link (master branch) of the commit ? Do we have any idea when this should land in Android N branch ?

**Comment by kalyankondapally** [comment]
https://android.googlesource.com/platform/frameworks/compile/libbcc/+/48ef3bd9fbbe6824d807534706f4a8418a282ed0 
? Did this land in any of the latest Android N 7.1 branches ?

**Comment by qiming-shi** [comment]
@kalyankondapally You can cherry-pick the patch from https://android-review.googlesource.com/#/c/238595/

Thanks

**Comment by kalyankondapally** [comment]
Done, Next repo sync should have it.
