### ISSUE TITLE
Android N CTS CtsGraphicsTestCases#testInflate failure

### ISSUE THREAD

**Issue by foolmm** [android-ia/manifest#12]
In CtsGraphicsTestCases, android.graphics.drawable.cts.AnimatedVectorDrawableTest#testInflate failed due to "Test failed to run to completion. Reason: 'Test run failed to complete. Expected 1072 tests, received 598'. Check device logcat for details"

**Comment by txu4** [comment]
It can pass on my side, maybe random issue, please double check @foolmm 

you can run below command in CTS v2 console.

run cts -m CtsGraphicsTestCases --disable-reboot --skip-preconditions --skip-device-info --abi x86_64 -t android.graphics.drawable.cts.AnimatedVectorDrawableTest#testInflate

**Comment by foolmm** [comment]
Tried with the command, it shows passed.
