### ISSUE TITLE
Android N CTS CtsGraphicsTestCases#testSingleFrameAnimation failure

### ISSUE THREAD

**Issue by foolmm** [android-ia/manifest#13]
In CtsGraphicsTestCases, android.graphics.drawable.cts.AnimatedVectorDrawableTest#testSingleFrameAnimation failed due to "android.util.AndroidRuntimeException: Animators may only be run on Looper threads"

**Comment by txu4** [comment]
Can be reproduced w/ below command in Cts console

#run cts -m CtsGraphicsTestCases --disable-reboot --skip-preconditions --skip-device-info --abi x86_64 -t android.graphics.drawable.cts.AnimatedVectorDrawableTest#testSingleFrameAnimation

**Comment by txu4** [comment]
11-17 06:24:47.327  4896  4912 W Resources: Drawable android.graphics.cts:drawable/avd_single_frame has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
11-17 06:24:47.327  4896  4912 W Resources: java.lang.RuntimeException
11-17 06:24:47.327  4896  4912 W Resources:     at android.content.res.Resources.getDrawable(Resources.java:746)
11-17 06:24:47.327  4896  4912 W Resources:     at android.graphics.drawable.cts.AnimatedVectorDrawableTest.testSingleFrameAnimation(AnimatedVectorDrawableTest.java:145)
11-17 06:24:47.327  4896  4912 W Resources:     at java.lang.reflect.Method.invoke(Native Method)
11-17 06:24:47.327  4896  4912 W Resources:     at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
11-17 06:24:47.327  4896  4912 W Resources:     at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)
11-17 06:24:47.327  4896  4912 W Resources:     at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
11-17 06:24:47.327  4896  4912 W Resources:     at junit.framework.TestCase.runBare(TestCase.java:134)
11-17 06:24:47.327  4896  4912 W Resources:     at junit.framework.TestResult$1.protect(TestResult.java:115)
11-17 06:24:47.327  4896  4912 W Resources:     at android.support.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:77)
11-17 06:24:47.327  4896  4912 W Resources:     at junit.framework.TestResult.run(TestResult.java:118)
11-17 06:24:47.327  4896  4912 W Resources:     at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:55)
11-17 06:24:47.327  4896  4912 W Resources:     at junit.framework.TestCase.run(TestCase.java:124)
11-17 06:24:47.327  4896  4912 W Resources:     at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
11-17 06:24:47.327  4896  4912 W Resources:     at android.support.test.internal.runner.junit3.AndroidTestSuite$1.run(AndroidTestSuite.java:97)
11-17 06:24:47.327  4896  4912 W Resources:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
11-17 06:24:47.327  4896  4912 W Resources:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-17 06:24:47.327  4896  4912 W Resources:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-17 06:24:47.327  4896  4912 W Resources:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-17 06:24:47.327  4896  4912 W Resources:     at java.lang.Thread.run(Thread.java:761)

11-17 06:24:47.338  4896  4912 I TestRunner: failed: testSingleFrameAnimation(android.graphics.drawable.cts.AnimatedVectorDrawableTest)
11-17 06:24:47.338  4896  4912 I TestRunner: ----- begin exception -----
11-17 06:24:47.338  4896  4912 I TestRunner: android.util.AndroidRuntimeException: Animators may only be run on Looper threads
11-17 06:24:47.338  4896  4912 I TestRunner:    at android.animation.ValueAnimator.start(ValueAnimator.java:969)
11-17 06:24:47.338  4896  4912 I TestRunner:    at android.animation.ValueAnimator.start(ValueAnimator.java:1011)
11-17 06:24:47.338  4896  4912 I TestRunner:    at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
11-17 06:24:47.338  4896  4912 I TestRunner:    at android.animation.AnimatorSet.start(AnimatorSet.java:678)
11-17 06:24:47.338  4896  4912 I TestRunner:    at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:807)
11-17 06:24:47.338  4896  4912 I TestRunner:    at android.animation.AnimatorSet.start(AnimatorSet.java:640)
11-17 06:24:47.338  4896  4912 I TestRunner:    at android.animation.AnimatorSet.start(AnimatorSet.java:678)
11-17 06:24:47.338  4896  4912 I TestRunner:    at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:807)
11-17 06:24:47.338  4896  4912 I TestRunner:    at android.animation.AnimatorSet.start(AnimatorSet.java:640)
11-17 06:24:47.338  4896  4912 I TestRunner:    at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorUI.start(AnimatedVectorDrawable.java:954)
11-17 06:24:47.338  4896  4912 I TestRunner:    at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.transferPendingActions(AnimatedVectorDrawable.java:1618)
11-17 06:24:47.338  4896  4912 I TestRunner:    at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.-wrap0(AnimatedVectorDrawable.java)
11-17 06:24:47.338  4896  4912 I TestRunner:    at android.graphics.drawable.AnimatedVectorDrawable.fallbackOntoUI(AnimatedVectorDrawable.java:505)
11-17 06:24:47.338  4896  4912 I TestRunner:    at android.graphics.drawable.AnimatedVectorDrawable.draw(AnimatedVectorDrawable.java:247)
11-17 06:24:47.338  4896  4912 I TestRunner:    at android.graphics.drawable.cts.AnimatedVectorDrawableTest.testSingleFrameAnimation(AnimatedVectorDrawableTest.java:159)
11-17 06:24:47.338  4896  4912 I TestRunner:    at java.lang.reflect.Method.invoke(Native Method)

**Comment by txu4** [comment]
It's a regression. The same case can pass on N MR0 build.

**Comment by foolmm** [comment]
With new CTS package compiled from github code, this issue is gone. Close it.
