### ISSUE TITLE
Android N CTS CtsRenderscriptTestCases 444 of 733 failure

### ISSUE THREAD

**Issue by foolmm** [android-ia/manifest#15]

**Comment by kalyankondapally** [comment]
This should be fixed with LLVM patch right ?

**Comment by foolmm** [comment]
Github AOSP is android-7.1.0_r4. We used android CTS version is 7.0_r3 to run CTS test got more failure cases. With android CTS pakage built out from github AOSP, all CtsRenderscriptTestCases passed.
