### ISSUE TITLE
fix typo in the manifest

### ISSUE THREAD

**Issue by cmsanta** [android-ia/manifest#18]
[  0% 60/7112] build /home/csanta/android/out/target/product/androidia_64/obj/KERNEL_OBJ/.config
FAILED: /bin/bash -c "(mkdir -p /home/csanta/android/out/target/product/androidia_64/obj/KERNEL_OBJ && cat device/intel/android_ia/kernel_config/kernel_64_defconfig > /home/csanta/android/out/target/product/androidia_64/obj/KERNEL_OBJ/.config ) && (make -j36 -C kernel/android_ia O=/home/csanta/android/out/target/product/androidia_64/obj/KERNEL_OBJ ARCH=x86_64 CROSS_COMPILE=\"\" KCFLAGS=\"\" KAFLAGS=\"\"  INSTALL_MOD_PATH=/home/csanta/android/out/target/product/androidia_64/system oldnoconfig )"
make: *** kernel/android_ia: No such file or directory.  Stop.
ninja: build stopped: subcommand failed.
make: *** [ninja_wrapper] Error 1
make: Leaving directory `/home/csanta/android'

**Comment by cmsanta** [comment]
@kalyankondapally  I guess my push got directly merged?

**Comment by kalyankondapally** [comment]
Thats fine usually u can also add closes <issue no> to close the issue directly.
